[tool.poetry]
name = "nonebot-plugin-l4d2-server"
version = "0.5.5.3"
description = "L4D2 server related operations plugin for NoneBot2"
authors = ["Agnes_Digital <Z735803792@163.com>"]
license = "GPLv3"
readme = "README.md"
homepage = "https://github.com/Agnes4m/nonebot_plugin_l4d2_server"
repository = "https://github.com/Agnes4m/nonebot_plugin_l4d2_server"
keywords = ["steam", "game", "l4d2", "nonebot2", "plugin"]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE","README.md"
]

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "^2.0.0rc4"
nonebot-adapter-onebot = ">=2.1.5"
nonebot_plugin_htmlrender = "^0.2.0.1"
nonebot_plugin_txt2img = ">=0.3.0"
nonebot_plugin_apscheduler = "^0.2.0"
asyncio = ">=3.4.3"
jinja2 = ">=3.0.0"
srctools="^2.3.9"
httpx = ">=0.23.3"
beautifulsoup4 = ">=4.8.0"
rcon = "^2.1.0"
pillow = "^9.3.0"
aiohttp = "^3.8.3"
pyunpack = "^0.3.0"
"ruamel.yaml" = "^0.17.21"
rarfile = "^4.0"
patool = "^1.12"
python-a2s = "^1.3.0"
amis-python = "^1.0.6"
jieba = "^0.42.1"
pandas = ">=1.5.2"
python-jose = "^3.3.0"
gitpython = ">=3.1.27"
attrs = "^23.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
